# Generated by Django 5.2.10 on 2026-01-09 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('email', 'email'), ('date', 'date'), ('password', 'password')], default='text', max_length=50)),
                ('order', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.dynamicformmodel')),
            ],
        ),
    ]
